# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backward_ll_cpp <- function(Gamma, p) {
    .Call(`_HiddenStateModels_backward_ll_cpp`, Gamma, p)
}

backward_prob_cpp <- function(Gamma, p) {
    .Call(`_HiddenStateModels_backward_prob_cpp`, Gamma, p)
}

forward_ll_cpp <- function(Gamma, p, delta) {
    .Call(`_HiddenStateModels_forward_ll_cpp`, Gamma, p, delta)
}

forward_prob_cpp <- function(Gamma, p, delta) {
    .Call(`_HiddenStateModels_forward_prob_cpp`, Gamma, p, delta)
}

update_log_gamma_cpp <- function(log_alpha, log_beta, log_gamma, log_p_mat, log_ll) {
    .Call(`_HiddenStateModels_update_log_gamma_cpp`, log_alpha, log_beta, log_gamma, log_p_mat, log_ll)
}

